### ISSUE TITLE
Rune portals allow easy destruction of end portals.

### ISSUE THREAD

**Issue by SiliconEnt** [svenhjol/Charm#68]
I just updated to Charm 1.1.2, and gave myself some Vanilla end portal frames and Quark runes to test with. So far, I've discovered a few problems. The pattern is that while Vanilla end portal frames are indestructible, (barring glitches) the runed portal frames are about as fragile as torches.

Observed behavior:
1. The runed portal frames break instantly with any tool, including empty hand. They drop nothing.
2. The runed portal blocks are instantly destroyed by explosions, including those of blue wither skulls.

Expected behavior:
1. The runed portal blocks should not be breakable in survival – the same as Vanilla end portal frames.
2. The runed portal blocks should have the same blast resistance as the Vanilla end portal frame, and should be equally wither-proof.

**Comment by svenhjol** [comment]
Thanks for the report. This has been fixed in 1.1.3, will release later.

**Comment by SiliconEnt** [comment]
Thanks so much for developing this mod! It really fills out the corners of my packs!

This should maybe be reopened or split into another issue though. The blocks are no longer breakable by hand, tool, or generic explosions, but are still broken by Blue Wither Skulls. They apparently haven't been flagged as wither-proof like Vanilla portal frames, so the Blue Skull still ignores their blast resistance value like it does for normal blocks.
